language: go
go:
  - 1.9
  - 1.8

install:
  - go get github.com/golang/dep/cmd/dep
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - dep ensure

script:
  - go list -f '"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | grep -v vendor/ | grep -v cmd/ | xargs -L 1 sh -c
  - $GOPATH/bin/gover
  - $GOPATH/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
