
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.41"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/hcl"

[[constraint]]
  name = "github.com/jjeffery/errors"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"
